### ISSUE TITLE
Incorrect Path for Access Control Scopes

### ISSUE THREAD

**Issue by markh0338** [automateyournetwork/ACEye#66]
In the make_directories function, the "Access Control Scopes" directory is created, however, when the various files are being written, "Access Control Scope" is used in the path. This leads to a file not found error.

FileNotFoundError: [Errno 2] No such file or directory: 'Access Control Scope/JSON/Access Control Scope.json'

**Comment by automateyournetwork** [comment]
Thank you for opening this issue I have patched the path and it is fixed in both the git repo and the pypi you want version 1.1.82 or beyond if you pip install aceye -U it should upgrade and fix this for you! Thanks again!
